name: Flutter QA workflow

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: 3.10.5
  CHANNEL: stable
  ARCH: x64

jobs:
  build:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: ${{ env.CHANNEL }}
          architecture: ${{ env.ARCH }}

      - name: Creating .env file and populate with variables
        run: |
          echo "BASE_URL=${{ secrets.BASE_URL }}" > .env
          cat .env

      - name: Install dependencies
        run: flutter pub get

      - name: Running build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Fix lint rules breaker
        run: dart fix --apply

      - name: Formatting lib folder
        run: dart format lib

      - name: Running unit tests
        run: flutter test

      - name: Setup Android Emulator
        run: |
          echo "y" | sdkmanager "system-images;android-29;google_apis;x86_64"
          echo "no" | avdmanager --verbose create avd --force --name "flutter_test" --package "system-images;android-29;google_apis;x86_64" --tag "google_apis" --abi "x86_64"

      - name: Launch Android Emulator
        run: |
          emulator -avd flutter_test -no-skin -no-audio -no-window -accel on

      - name: Wait for Emulator to be ready
        run: |
          flutter emulators --launch flutter_test
          flutter devices

      - name: Running integration tests
        run: flutter test integration_test/start_app.dart
